controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    rizon_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    streaming_position_controller:
      type: streaming_position_controller/StreamingPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gpio_controller:
      type: gpio_controller/GPIOController

    flexiv_robot_states_broadcaster:
      type: flexiv_robot_states_broadcaster/FlexivRobotStatesBroadcaster

rizon_arm_controller:
  ros__parameters:
    joints:
      - $(var robot_sn)_joint1
      - $(var robot_sn)_joint2
      - $(var robot_sn)_joint3
      - $(var robot_sn)_joint4
      - $(var robot_sn)_joint5
      - $(var robot_sn)_joint6
      - $(var robot_sn)_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

streaming_position_controller:
  ros__parameters:
    joints:
      - $(var robot_sn)_joint1
      - $(var robot_sn)_joint2
      - $(var robot_sn)_joint3
      - $(var robot_sn)_joint4
      - $(var robot_sn)_joint5
      - $(var robot_sn)_joint6
      - $(var robot_sn)_joint7
