# Request

# Empty trigger

---
# Result

# Array of pose
vision_msgs/Detection3DArray poses

# 2D Detections for corrsponding 3D poses (optional)
# Note, if not empty, number of elements should match of those in poses field
vision_msgs/Detection2DArray detections

---
# Feedback
int32 progress
