# Request

# Optional parameters to add in order to to integrate with Segment Anything
bool use_initial_hint
geometry_msgs/Point initial_hint

---
# Result

# Array of objects
ObjectInfo[] objects
---
# Feedback
int32 progress
