# Request

# Object id to get pose of. This should match the one provided by the GetObjects action

# ObjectID
int32 object_id

# Object class
string class_id

---
# Result

# Pose of the object
geometry_msgs/Pose object_pose

---
# Feedback
int32 progress
