# This action starts the multi-object pick and place workflow

# Request

# Mode values
uint8 SINGLE_BIN = 0
uint8 MULTI_BIN = 1

# Mode of operation for multi-object pick and place. 
# If mode = SINGLE_BIN, then the first pose in the target_pose is used for all the objects
# If mode = MULTI_BIN, then the class_ids and target_pose must be of equal lengths
# and index is used to determine the correspondence between class_name and target pose
# 
# Examples:
# 
# Example (SINGLE_BIN): the first pose in target_poses is used for all objects
# mode: 0  # SINGLE_BIN
# target_poses:
#   header: { frame_id: "world" }
#   poses:
#     - position: {x: 0.50, y: 0.00, z: 0.20}
#       orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
# class_ids: ["cup", "bottle", "box"]
# 
# Example (MULTI_BIN): class_ids and target_poses.poses must have the same length and order
# mode: 1  # MULTI_BIN
# target_poses:
#   header: { frame_id: "world" }
#   poses:
#     - position: {x: 0.50, y: 0.00, z: 0.20}  # for "cup"
#       orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
#     - position: {x: 0.60, y: 0.10, z: 0.20}  # for "bottle"
#       orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
#     - position: {x: 0.40, y: -0.10, z: 0.20} # for "box"
#       orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
# class_ids: ["cup", "bottle", "box"]
uint8 mode

# Pose of the location or bin to drop all the objects
geometry_msgs/PoseArray target_poses
string[] class_ids

---
# Result

# Status field constants
uint8 FAILED = 0
uint8 SUCCESS = 1
uint8 PARTIAL_SUCCESS = 2
uint8 INCOMPLETE = 3
uint8 UNKNOWN = 4

# Indicates the result of the request.
uint8 workflow_status
string workflow_summary

---
# Feedback
string message
