# Request

# Choose between using a point or bounding box as the initial hint
bool use_point_hint

# Initial point hint for where to look for the object
vision_msgs/Point2D initial_hint_point

# Initial bounding box hint for where to look for the object
vision_msgs/BoundingBox2D initial_hint_bbox

---
# Result

# Single detected object
vision_msgs/Detection2D detection

# Segmentation Mask of that object
sensor_msgs/Image segmentation_mask

---
# Feedback
int32 progress
