# Request

geometry_msgs/PoseStamped goal_pose
---
# Result

bool success

---
# Feedback
int32 status

# Make sure this aligns with the values stored in ros_python_utils/gear_assembly.py
int32 IDLE = 0
int32 INSERTING = 1
int32 COMPLETED = 2
int32 FAILED = 3
