# Request

# Defines the object to be picked and placed at a give pose

# ObjectID
int32 object_id

# Object class
string class_id

# Pose of the location to place the object
geometry_msgs/Pose place_pose

# Params used by the gear assembly policy
bool use_joint_space_planner_for_place_pose

sensor_msgs/JointState target_joint_state_for_place_pose

# Keep gripper closed after completion
bool keep_gripper_closed_after_completion

# Position for gripper to closed, 0.623 is completely closed and
# 0.0 is open. Some objects might need 0.45 or also 0.55. This parameter
# is important in Isaac Sim since if you close the gripper too tightly, the
# object will fly out of the gripper and the robot will go into a regressive physics
# position causing indeterminate behavior.
float64 gripper_closed_position

# This is used to verify pose estimation + calibration error to get a sense
bool only_perform_place

---
# Result

# Indicates if the pick and place is successful
bool success

---
# Feedback
int32 progress
