# Request
# List of objects that update the mesh file paths for foundation pose
int32[] object_ids
string[] mesh_file_paths
---
# Response
# Success or failure
bool success
string message
int32[] failed_ids